/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import javax.swing.ImageIcon;
import views.CounselorManagement;

/**
 *
 * @author Heiner
 */
public class Dashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Dashboard.class.getName());

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/resources/bc_logo2.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DashboardPanel = new javax.swing.JPanel();
        CounselorPanel = new javax.swing.JPanel();
        CounselorBtn = new javax.swing.JButton();
        CounselorTxt = new javax.swing.JLabel();
        AppointmentPanel = new javax.swing.JPanel();
        AppointmentsBtn = new javax.swing.JButton();
        AppointmentTxt = new javax.swing.JLabel();
        AppointmentTxt2 = new javax.swing.JLabel();
        FeedbackPanel = new javax.swing.JPanel();
        FeedbackBtn = new javax.swing.JButton();
        FeedbaclTxt = new javax.swing.JLabel();
        TitleTxt = new javax.swing.JLabel();
        WMSTxt = new javax.swing.JLabel();
        ExitBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 153, 0));

        DashboardPanel.setBackground(new java.awt.Color(0, 204, 204));

        CounselorPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 102, 0)));

        CounselorBtn.setBackground(new java.awt.Color(255, 122, 53));
        CounselorBtn.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        CounselorBtn.setText("Counselors");
        CounselorBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CounselorBtn.setName("CounselorBtn"); // NOI18N
        CounselorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CounselorBtnActionPerformed(evt);
            }
        });

        CounselorTxt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CounselorTxt.setText("View our available Counselors.");

        javax.swing.GroupLayout CounselorPanelLayout = new javax.swing.GroupLayout(CounselorPanel);
        CounselorPanel.setLayout(CounselorPanelLayout);
        CounselorPanelLayout.setHorizontalGroup(
            CounselorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CounselorPanelLayout.createSequentialGroup()
                .addGroup(CounselorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CounselorPanelLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(CounselorBtn))
                    .addGroup(CounselorPanelLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(CounselorTxt)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        CounselorPanelLayout.setVerticalGroup(
            CounselorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CounselorPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(CounselorTxt)
                .addGap(34, 34, 34)
                .addComponent(CounselorBtn)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        AppointmentPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 102, 0)));

        AppointmentsBtn.setBackground(new java.awt.Color(255, 122, 53));
        AppointmentsBtn.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        AppointmentsBtn.setText("Appointments");
        AppointmentsBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AppointmentsBtn.setName(""); // NOI18N
        AppointmentsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AppointmentsBtnActionPerformed(evt);
            }
        });

        AppointmentTxt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        AppointmentTxt.setText("Make an appointment with");

        AppointmentTxt2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        AppointmentTxt2.setText("one of our counselors.");

        javax.swing.GroupLayout AppointmentPanelLayout = new javax.swing.GroupLayout(AppointmentPanel);
        AppointmentPanel.setLayout(AppointmentPanelLayout);
        AppointmentPanelLayout.setHorizontalGroup(
            AppointmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AppointmentPanelLayout.createSequentialGroup()
                .addGroup(AppointmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AppointmentPanelLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(AppointmentsBtn))
                    .addGroup(AppointmentPanelLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(AppointmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AppointmentTxt)
                            .addGroup(AppointmentPanelLayout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(AppointmentTxt2)))))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        AppointmentPanelLayout.setVerticalGroup(
            AppointmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AppointmentPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(AppointmentTxt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(AppointmentTxt2)
                .addGap(18, 18, 18)
                .addComponent(AppointmentsBtn)
                .addGap(39, 39, 39))
        );

        FeedbackPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 102, 0)));

        FeedbackBtn.setBackground(new java.awt.Color(102, 0, 255));
        FeedbackBtn.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        FeedbackBtn.setText("Feedback");
        FeedbackBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        FeedbackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FeedbackBtnActionPerformed(evt);
            }
        });

        FeedbaclTxt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        FeedbaclTxt.setText("We appreciate your feedback.");

        javax.swing.GroupLayout FeedbackPanelLayout = new javax.swing.GroupLayout(FeedbackPanel);
        FeedbackPanel.setLayout(FeedbackPanelLayout);
        FeedbackPanelLayout.setHorizontalGroup(
            FeedbackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FeedbackPanelLayout.createSequentialGroup()
                .addGroup(FeedbackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FeedbackPanelLayout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(FeedbackBtn))
                    .addGroup(FeedbackPanelLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(FeedbaclTxt)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        FeedbackPanelLayout.setVerticalGroup(
            FeedbackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FeedbackPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(FeedbaclTxt)
                .addGap(34, 34, 34)
                .addComponent(FeedbackBtn)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        TitleTxt.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        TitleTxt.setForeground(new java.awt.Color(255, 255, 255));
        TitleTxt.setText("STUDENT WMS");

        WMSTxt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        WMSTxt.setForeground(new java.awt.Color(255, 255, 255));
        WMSTxt.setText("Wellness Management System");

        ExitBtn.setBackground(new java.awt.Color(255, 51, 51));
        ExitBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ExitBtn.setText("X");
        ExitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitBtnActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/download__3_-removebg-preview.png"))); // NOI18N

        javax.swing.GroupLayout DashboardPanelLayout = new javax.swing.GroupLayout(DashboardPanel);
        DashboardPanel.setLayout(DashboardPanelLayout);
        DashboardPanelLayout.setHorizontalGroup(
            DashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DashboardPanelLayout.createSequentialGroup()
                .addGroup(DashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DashboardPanelLayout.createSequentialGroup()
                        .addGroup(DashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(DashboardPanelLayout.createSequentialGroup()
                                .addGap(131, 131, 131)
                                .addComponent(FeedbackPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(AppointmentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(CounselorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(DashboardPanelLayout.createSequentialGroup()
                                .addGap(186, 186, 186)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(DashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TitleTxt)
                                    .addComponent(WMSTxt))))
                        .addGap(0, 176, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DashboardPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ExitBtn)))
                .addContainerGap())
        );
        DashboardPanelLayout.setVerticalGroup(
            DashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DashboardPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DashboardPanelLayout.createSequentialGroup()
                        .addComponent(ExitBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TitleTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(WMSTxt)
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DashboardPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(DashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FeedbackPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AppointmentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CounselorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(185, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(DashboardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(DashboardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CounselorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CounselorBtnActionPerformed
        new CounselorManagement().setVisible(true); // Open new form
        dispose();
    }//GEN-LAST:event_CounselorBtnActionPerformed

    private void ExitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitBtnActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ExitBtnActionPerformed

    private void FeedbackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FeedbackBtnActionPerformed
        // TODO add your handling code here:
        new views.FeedbackForm().setVisible(true);
    this.dispose();
        
    }//GEN-LAST:event_FeedbackBtnActionPerformed

    private void AppointmentsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AppointmentsBtnActionPerformed
        // TODO add your handling code here:
        new views.AppointmentForm().setVisible(true);
    this.dispose();
    }//GEN-LAST:event_AppointmentsBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Dashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AppointmentPanel;
    private javax.swing.JLabel AppointmentTxt;
    private javax.swing.JLabel AppointmentTxt2;
    private javax.swing.JButton AppointmentsBtn;
    private javax.swing.JButton CounselorBtn;
    private javax.swing.JPanel CounselorPanel;
    private javax.swing.JLabel CounselorTxt;
    private javax.swing.JPanel DashboardPanel;
    private javax.swing.JButton ExitBtn;
    private javax.swing.JButton FeedbackBtn;
    private javax.swing.JPanel FeedbackPanel;
    private javax.swing.JLabel FeedbaclTxt;
    private javax.swing.JLabel TitleTxt;
    private javax.swing.JLabel WMSTxt;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
