/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.Feedback;

/**
 *
 * @author Heiner
 */
public class FeedbackForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FeedbackForm.class.getName());
    private Feedback feedback;
    private DefaultTableModel tableModel;

    public FeedbackForm() {
        tableModel = new DefaultTableModel(new Object[]{"Rating", "Comments"}, 0);
        initComponents();
        FeedbackTable.setModel(tableModel);
        feedback = new Feedback(tableModel, FeedbackTable);
             
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FeedbackPanel = new javax.swing.JPanel();
        MenuPanel = new javax.swing.JPanel();
        MenuTxt = new javax.swing.JLabel();
        homeBtn = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();
        FeedbackTitleTxt = new javax.swing.JLabel();
        RatingPanel = new javax.swing.JPanel();
        RatingTxt = new javax.swing.JLabel();
        RatingClearBtn = new javax.swing.JButton();
        Star1 = new javax.swing.JRadioButton();
        Star2 = new javax.swing.JRadioButton();
        Star3 = new javax.swing.JRadioButton();
        Star4 = new javax.swing.JRadioButton();
        Star5 = new javax.swing.JRadioButton();
        CommentTxt = new javax.swing.JLabel();
        CommentTxtArea = new javax.swing.JScrollPane();
        CommentsTxtArea = new javax.swing.JTextArea();
        SubmitBtn = new javax.swing.JButton();
        FeedbackScrollPanel = new javax.swing.JScrollPane();
        FeedbackTable = new javax.swing.JTable();
        DeleteBtn = new javax.swing.JButton();
        ViewBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        FeedbackPanel.setBackground(new java.awt.Color(255, 153, 0));

        MenuPanel.setBackground(new java.awt.Color(255, 102, 0));

        MenuTxt.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        MenuTxt.setText("MENU");

        homeBtn.setBackground(new java.awt.Color(255, 0, 0));
        homeBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        homeBtn.setForeground(new java.awt.Color(255, 255, 255));
        homeBtn.setText("HOME");
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MenuPanelLayout = new javax.swing.GroupLayout(MenuPanel);
        MenuPanel.setLayout(MenuPanelLayout);
        MenuPanelLayout.setHorizontalGroup(
            MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuPanelLayout.createSequentialGroup()
                .addGroup(MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MenuPanelLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(MenuTxt))
                    .addGroup(MenuPanelLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(homeBtn)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        MenuPanelLayout.setVerticalGroup(
            MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MenuTxt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(homeBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        exitBtn.setBackground(new java.awt.Color(255, 51, 0));
        exitBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        exitBtn.setForeground(new java.awt.Color(255, 255, 255));
        exitBtn.setText("x");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });

        FeedbackTitleTxt.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        FeedbackTitleTxt.setForeground(new java.awt.Color(255, 255, 255));
        FeedbackTitleTxt.setText("Feedback");

        RatingPanel.setBackground(new java.awt.Color(204, 204, 204));
        RatingPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 102, 0)));

        RatingTxt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        RatingTxt.setText("Rating");

        RatingClearBtn.setBackground(new java.awt.Color(255, 51, 51));
        RatingClearBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        RatingClearBtn.setForeground(new java.awt.Color(255, 255, 255));
        RatingClearBtn.setText("Clear");
        RatingClearBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RatingClearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RatingClearBtnActionPerformed(evt);
            }
        });

        Star1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/starUnselected.png"))); // NOI18N
        Star1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Star1ActionPerformed(evt);
            }
        });

        Star2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/starUnselected.png"))); // NOI18N
        Star2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Star2ActionPerformed(evt);
            }
        });

        Star3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/starUnselected.png"))); // NOI18N
        Star3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Star3ActionPerformed(evt);
            }
        });

        Star4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/starUnselected.png"))); // NOI18N
        Star4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Star4ActionPerformed(evt);
            }
        });

        Star5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/starUnselected.png"))); // NOI18N
        Star5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Star5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout RatingPanelLayout = new javax.swing.GroupLayout(RatingPanel);
        RatingPanel.setLayout(RatingPanelLayout);
        RatingPanelLayout.setHorizontalGroup(
            RatingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RatingPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(RatingTxt)
                .addGap(150, 150, 150))
            .addGroup(RatingPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RatingClearBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RatingPanelLayout.createSequentialGroup()
                .addContainerGap(391, Short.MAX_VALUE)
                .addComponent(Star1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Star2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Star3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Star4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Star5)
                .addGap(120, 120, 120))
        );
        RatingPanelLayout.setVerticalGroup(
            RatingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RatingPanelLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(RatingTxt)
                .addGap(18, 18, 18)
                .addGroup(RatingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Star1)
                    .addComponent(Star3)
                    .addComponent(Star4)
                    .addComponent(Star5)
                    .addComponent(Star2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 263, Short.MAX_VALUE)
                .addComponent(RatingClearBtn)
                .addContainerGap())
        );

        CommentTxt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        CommentTxt.setForeground(new java.awt.Color(255, 255, 255));
        CommentTxt.setText("Any Comments?");

        CommentTxtArea.setBackground(new java.awt.Color(204, 204, 204));

        CommentsTxtArea.setBackground(new java.awt.Color(204, 204, 204));
        CommentsTxtArea.setColumns(20);
        CommentsTxtArea.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CommentsTxtArea.setRows(5);
        CommentsTxtArea.setText("(if any)Enter your comments here...");
        CommentTxtArea.setViewportView(CommentsTxtArea);

        SubmitBtn.setBackground(new java.awt.Color(255, 51, 51));
        SubmitBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        SubmitBtn.setForeground(new java.awt.Color(255, 255, 255));
        SubmitBtn.setText("Submit");
        SubmitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitBtnActionPerformed(evt);
            }
        });

        FeedbackTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        FeedbackScrollPanel.setViewportView(FeedbackTable);

        DeleteBtn.setBackground(new java.awt.Color(255, 51, 51));
        DeleteBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        DeleteBtn.setForeground(new java.awt.Color(255, 255, 255));
        DeleteBtn.setText("Delete");
        DeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteBtnActionPerformed(evt);
            }
        });

        ViewBtn.setBackground(new java.awt.Color(255, 51, 51));
        ViewBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ViewBtn.setForeground(new java.awt.Color(255, 255, 255));
        ViewBtn.setText("View");
        ViewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FeedbackPanelLayout = new javax.swing.GroupLayout(FeedbackPanel);
        FeedbackPanel.setLayout(FeedbackPanelLayout);
        FeedbackPanelLayout.setHorizontalGroup(
            FeedbackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FeedbackPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(FeedbackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FeedbackPanelLayout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addComponent(FeedbackTitleTxt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(exitBtn))
                    .addGroup(FeedbackPanelLayout.createSequentialGroup()
                        .addGroup(FeedbackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(FeedbackPanelLayout.createSequentialGroup()
                                .addGap(111, 111, 111)
                                .addGroup(FeedbackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(SubmitBtn)
                                    .addComponent(CommentTxtArea, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CommentTxt)))
                            .addGroup(FeedbackPanelLayout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addGroup(FeedbackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(FeedbackPanelLayout.createSequentialGroup()
                                        .addComponent(DeleteBtn)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(ViewBtn))
                                    .addComponent(FeedbackScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(FeedbackPanelLayout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addComponent(RatingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        FeedbackPanelLayout.setVerticalGroup(
            FeedbackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FeedbackPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FeedbackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FeedbackPanelLayout.createSequentialGroup()
                        .addComponent(MenuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(4, 4, 4))
                    .addGroup(FeedbackPanelLayout.createSequentialGroup()
                        .addComponent(exitBtn)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(FeedbackPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(FeedbackTitleTxt)
                .addGap(18, 18, 18)
                .addComponent(RatingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CommentTxt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CommentTxtArea, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(SubmitBtn)
                .addGap(50, 50, 50)
                .addComponent(FeedbackScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FeedbackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DeleteBtn)
                    .addComponent(ViewBtn))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FeedbackPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FeedbackPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        System.exit(0);

    }//GEN-LAST:event_exitBtnActionPerformed

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        new Dashboard().setVisible(true); // Open new form
        this.dispose();
    }//GEN-LAST:event_homeBtnActionPerformed

    private void RatingClearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RatingClearBtnActionPerformed
        Star1.setSelected(false);
        Star2.setSelected(false);
        Star3.setSelected(false);
        Star4.setSelected(false);
        Star5.setSelected(false);
    }//GEN-LAST:event_RatingClearBtnActionPerformed

    private void SubmitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitBtnActionPerformed
        try {
        int rating = 0;
        if (Star5.isSelected()) rating = 5;
        else if (Star4.isSelected()) rating = 4;
        else if (Star3.isSelected()) rating = 3;
        else if (Star2.isSelected()) rating = 2;
        else if (Star1.isSelected()) rating = 1;
        String comments = CommentsTxtArea.getText().trim();

        if (rating == 0) {
            JOptionPane.showMessageDialog(this, "Please select a rating.");
            return;
        }

        feedback.setFeedbackData(rating, comments);
        feedback.addData();
        JOptionPane.showMessageDialog(this, "Feedback submitted");

        Star1.setSelected(false);
        Star2.setSelected(false);
        Star3.setSelected(false);
        Star4.setSelected(false);
        Star5.setSelected(false);
        CommentsTxtArea.setText("");
    } catch (IllegalArgumentException e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
    }
    }//GEN-LAST:event_SubmitBtnActionPerformed

    private void DeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBtnActionPerformed
        int selectedRow = FeedbackTable.getSelectedRow();
        if (selectedRow != -1) {
            feedback.removeData(selectedRow);
            JOptionPane.showMessageDialog(this, "Feedback deleted");
        } else {
            JOptionPane.showMessageDialog(this, "Please select a row to delete.");
        }
    }//GEN-LAST:event_DeleteBtnActionPerformed

    private void ViewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewBtnActionPerformed
        if (tableModel.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "No feedback available to display in the table.", "View Feedback", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        tableModel.fireTableDataChanged();
    }//GEN-LAST:event_ViewBtnActionPerformed

    private void Star1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Star1ActionPerformed
        // TODO add your handling code here:
         Star1.setSelected(true);  // Light up star1
        Star2.setSelected(false); // Dim star2 and higher
        Star3.setSelected(false);
        Star4.setSelected(false);
        Star5.setSelected(false);
    }//GEN-LAST:event_Star1ActionPerformed

    private void Star2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Star2ActionPerformed
        // TODO add your handling code here:
        Star1.setSelected(true);  // Light up star1 and star2
        Star2.setSelected(true);
        Star3.setSelected(false); // Dim star3 and higher
        Star4.setSelected(false);
        Star5.setSelected(false);
    }//GEN-LAST:event_Star2ActionPerformed

    private void Star3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Star3ActionPerformed
        // TODO add your handling code here:
        Star1.setSelected(true);  // Light up star1, star2, and star3
        Star2.setSelected(true);
        Star3.setSelected(true);
        Star4.setSelected(false); // Dim star4 and higher
        Star5.setSelected(false);
    }//GEN-LAST:event_Star3ActionPerformed

    private void Star4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Star4ActionPerformed
        // TODO add your handling code here:
        Star1.setSelected(true);  // Light up star1, star2, star3, and star4
        Star2.setSelected(true);
        Star3.setSelected(true);
        Star4.setSelected(true);
        Star5.setSelected(false); // Dim star5
    }//GEN-LAST:event_Star4ActionPerformed

    private void Star5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Star5ActionPerformed
        // TODO add your handling code here:
        Star1.setSelected(true);  // Light up all stars
        Star2.setSelected(true);
        Star3.setSelected(true);
        Star4.setSelected(true);
        Star5.setSelected(true);
    }//GEN-LAST:event_Star5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        java.awt.EventQueue.invokeLater(() -> new FeedbackForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CommentTxt;
    private javax.swing.JScrollPane CommentTxtArea;
    private javax.swing.JTextArea CommentsTxtArea;
    private javax.swing.JButton DeleteBtn;
    private javax.swing.JPanel FeedbackPanel;
    private javax.swing.JScrollPane FeedbackScrollPanel;
    private javax.swing.JTable FeedbackTable;
    private javax.swing.JLabel FeedbackTitleTxt;
    private javax.swing.JPanel MenuPanel;
    private javax.swing.JLabel MenuTxt;
    private javax.swing.JButton RatingClearBtn;
    private javax.swing.JPanel RatingPanel;
    private javax.swing.JLabel RatingTxt;
    private javax.swing.JRadioButton Star1;
    private javax.swing.JRadioButton Star2;
    private javax.swing.JRadioButton Star3;
    private javax.swing.JRadioButton Star4;
    private javax.swing.JRadioButton Star5;
    private javax.swing.JButton SubmitBtn;
    private javax.swing.JButton ViewBtn;
    private javax.swing.JButton exitBtn;
    private javax.swing.JButton homeBtn;
    // End of variables declaration//GEN-END:variables
}
